### PR TITLE
Remove ReplyTo and ReplyToArray classes

### PR DESCRIPTION
**Pull request by gil-l**
Remove ReplyTo and ReplyToArray classes in favor of simple email reply tos.

### CODE REVIEW

**Comment by pedrosan7os** [comment]
Is it necessary to support multiple replyTos per message? Isn't that going to complicate the interface?

**Comment by jcarvalho** [comment]
I agree with @pedrosan7os. Each sender may have one Reply To (which in most cases won't even be filled), and the UI to send a Message should show a Radio Box (i.e. only one option), allowing setting it to either:
- The system default no-reply
- The email of the current user (the value, not a special representation of 'this user')
- The email configured in the sender
- A text box allowing the user to input free-form text

**Comment by gil-l** [comment]
@pedrosan7os I guess not and not really. The interface right now is simply a set of checkbox inputs with the multiple sender reply tos (in the messages) and a multiple email input (in the sender) so it's not awfully complex. I think the API doesn't suffer much either. It's the same between this and radio buttons. I just want to point out that I don't see the point of restricting it to one email in terms of interface complexity. I have a question about that 'free-form' text box @jcarvalho I suppose that it's to be a single email input right? If it's a multiple then we may just be chucking work to the users. Besides that, I thought senders had reply tos precisely to restrict freedom in this, this input breaks that.

**Comment by gil-l** [comment]
In the end it was decided to drop the user and no-reply reply to options in favor of simplicity and user freedom.

**Pull request merged**
